### ISSUE TITLE
compile error by Qt5.14.2

### ISSUE THREAD

**Issue by isteelcx** [zcutech/NodeTiler#1]
see the details.

**Comment by isteelcx** [comment]
![图片](https://user-images.githubusercontent.com/45957575/204021592-4661276b-41cf-47c3-b9d2-9b3dac3e9e9b.png)

**Comment by zcutech** [comment]
It seems that Qt Creator has already set the Qt MinGW install path to the `CMAKE_PREFIX_PATH`, however, I used the CLion to build my project which had to APPEND Qt MinGW path and set it as builder working directory. To make it correct, just add `string(REGEX REPLACE "^.+;" "" QT_INSTALL_PATH "${QT_INSTALL_PATH}")`, and your `APPEND CMAKE_PREFIX_PATH` command should be wrote empty or correct path.

**Comment by isteelcx** [comment]
where can I add string(REGEX REPLACE "^.+;" "" QT_INSTALL_PATH "${QT_INSTALL_PATH}")?

**Comment by isteelcx** [comment]
> It seems that Qt Creator has already set the Qt MinGW install path to the `CMAKE_PREFIX_PATH`, however, I used the CLion to build my project which had to APPEND Qt MinGW path and set it as builder working directory. To make it correct, just add `string(REGEX REPLACE "^.+;" "" QT_INSTALL_PATH "${QT_INSTALL_PATH}")`, and your `APPEND CMAKE_PREFIX_PATH` command should be wrote empty or correct path.

thank you very much！
